---
- hosts: cupie
  roles:
    - role: letsencrypt
      tags: letsencrypt
      vars:
        dehydrated_ca: 'https://acme-v01.api.letsencrypt.org/directory'
        letsencrypt_certs:
          - host: [curiebot.ddns.net]
    - role: cupie
      tags: cupie
