nginx_server_name: curiebot.ddns.net
nginx_pid_file: null

dehydrated_repo: 'https://github.com/lukas2511/dehydrated.git'
dehydrated_commit: 'v0.4.0'

dehydrated_base_directory: '/etc/dehydrated'
dehydrated_certs_directory: '/etc/ssl/letsencrypt/certs'
dehydrated_accounts_directory: '{{ dehydrated_base_directory }}/accounts'
dehydrated_config_file: '/etc/dehydrated/config'
dehydrated_domains_file: '{{ dehydrated_base_directory }}/domains.txt'
dehydrated_software_directory: '/usr/local/dehydrated'
dehydrated_challenges_directory: '/var/www/letsencrypt'
# production CA URL:
# dehydrated_ca: 'htt ps://acme-v01.api.letsencrypt.org/directory'
dehydrated_ca: 'https://acme-staging.api.letsencrypt.org/directory'

letsencrypt_account_key: '{{ dehydrated_base_directory }}/private_key.pem'

letsencrypt_key_dir: '/etc/ssl/letsencrypt/keys'
letsencrypt_certs_dir: '/etc/ssl/letsencrypt/certs'

letsencrypt_key_dir_permissions: '0700'
letsencrypt_key_dir_owner: root
letsencrypt_key_dir_group: root

letsencrypt_certs: []

letsencrypt_user: 'www'
letsencrypt_group: 'www'

letsencrypt_certs_dir_permissions: '0755'
letsencrypt_certs_dir_owner: '{{ letsencrypt_user }}'
letsencrypt_certs_dir_group: '{{ letsencrypt_group }}'

letsencrypt_default_key_owner: 'root'
letsencrypt_default_key_group: 'root'
letsencrypt_default_key_permissions: '0600'

# the minimum age (in days) after which a certificate will be renewed
letsencrypt_min_renewal_age: 60

# the days of a month the cronjob should be run. Make sure to run it rather often, three times per month is a pretty
# good value. It does not harm to run it often, as it will only regenerate certificates that have passed a certain age
# (60 days by default).
letsencrypt_cronjob_daysofmonth: "*"
