---
dependencies:
  - role: jdauphant.nginx
    become: true
    tags: [cupie-nginx]
    nginx_user: www
    nginx_events_param:
      - worker_connections 512
    nginx_sites:
      cupie:
        - listen 443 ssl
        - keepalive_timeout 70
        - 'ssl_certificate /etc/ssl/letsencrypt/certs/{{ cupie_server_name }}/fullchain.pem'
        - 'ssl_certificate_key /etc/ssl/letsencrypt/certs/{{ cupie_server_name }}/privkey.pem'
        - 'server_name {{ cupie_server_name }}'
        - ssl_protocols TLSv1 TLSv1.1 TLSv1.2
        - ssl_prefer_server_ciphers on
        - ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH"
        - ssl_ecdh_curve secp384r1
        - ssl_session_cache shared:SSL:10m
        - ssl_session_tickets off
        - ssl_stapling on
        - ssl_stapling_verify on
        # TODO: Specify DNS resolvers -- I'd like to switch our DNS over to AWS Route 53
        # - resolver $DNS-IP-1 $DNS-IP-2 valid=300s
        # - resolver_timeout 5s
        # TODO: Enable HSTS
        # - add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
        - add_header X-Frame-Options DENY
        - add_header X-Content-Type-Options nosniff
        - location ~ ^/api/(record|document|encode)$ {
              proxy_set_header Host $host;
              expires 1y;
              proxy_pass "http://127.0.0.1:5000/$1$is_args$args";
          }
        - location /api/ {
              proxy_set_header Host $host;
              proxy_pass "http://127.0.0.1:5000/";
          }
        - location / {
              alias {{ cupie_www }};
              try_files $uri /index.html;
          }
